### ISSUE TITLE
Example data Vallet not working on EPFL Server

### ISSUE THREAD

**Issue by stefangachter** [SMAC-Group/ODyN#1]
I uploaded [INS+lidar.zip](https://github.com/SMAC-Group/ODyN/blob/master/data/vallet/INS%2Blidar.zip) and [configuration.RData](https://github.com/SMAC-Group/ODyN/blob/master/data/vallet/configuration.RData) successfully at https://odyn.epfl.ch/app_direct/odyn/ (dn rev: c6b6253, ROAMFREE rev: 86ccac8, built on 06-28-2022 09:30:30)
![image](https://user-images.githubusercontent.com/7974580/185947331-64d09141-fc4a-455a-84d4-a475713f580d.png)
![image](https://user-images.githubusercontent.com/7974580/185947611-253a91c5-ce4a-4cf7-bc39-d355a03d0080.png)
However, the processing fails
![image](https://user-images.githubusercontent.com/7974580/185947809-af04c0a7-3159-45b4-94fe-7b23d42410d9.png)
The state is available [here](https://odyn.epfl.ch/app_direct/odyn/?_state_id_=1012acc1b2fd739e)
How can I further investigate the issue? Is there some log file available?

Best regards
Stefan

**Comment by AurelienBrn** [comment]
Dear Stefan,

Thanks a lot for raising the issue.

ODyN engine was recently updated and the bug was fixed. 
Testing with the available data should now work on your side as well, following the procedure indicated in your ticket.

Let me know how it goes!

Kind regards,

Aurélien

**Comment by stefangachter** [comment]
Thanks, Aurelien, for taking care of the bug and fixing the engine. I can confirm that processing works for me now.
